import path from "path"
import { fileURLToPath } from "url"
import { Effect } from "effect"
import { AppFileSystem } from "@jyycode-ai/core/filesystem"
import { Global } from "@jyycode-ai/core/global"
import { Glob } from "@jyycode-ai/core/util/glob"
import * as Log from "@jyycode-ai/core/util/log"

const log = Log.create({ service: "builtin-roles" })

const ROLE_ID = /^[A-Za-z0-9][A-Za-z0-9_-]*$/

/**
 * Files of the built-in subagent roles that ship with jyycode. In a compiled
 * binary the map comes from `jyycode-builtin-roles.gen.ts` (generated by
 * script/build.ts), whose values are bundle-embedded file references. During
 * development the generated module does not exist, so the files are scanned
 * from the source tree instead. Keys are "<roleID>/<relative path>".
 */
let filesPromise: Promise<Record<string, string>> | undefined

function sourceTreeFiles(): Promise<Record<string, string>> {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "defaults", "role")
  return Glob.scan("**/*", { cwd: root, absolute: true, include: "file", dot: true })
    .then((matches) => {
      const result: Record<string, string> = {}
      for (const match of matches) {
        const relative = path.relative(root, match).split(path.sep).join("/")
        if (relative) result[relative] = match
      }
      return result
    })
    .catch(() => ({}))
}

function roleFiles(): Promise<Record<string, string>> {
  return (filesPromise ??=
    // @ts-expect-error - generated at build time, absent in development
    import("jyycode-builtin-roles.gen.ts")
      .then((module) => module.default as Record<string, string>)
      .catch(() => sourceTreeFiles()))
}

export function hasBuiltinRole(roleID: string, files: Record<string, string>) {
  return Object.keys(files).some((key) => key.startsWith(`${roleID}/`))
}

/**
 * Copy the bundled files of a built-in role into the user's role directory.
 * Runs at most once per role: an existing role directory is never touched, so
 * user modifications and deletions always win over the bundled defaults.
 */
export const seed = Effect.fn("BuiltinRoles.seed")(function* (roleID: string, fs: AppFileSystem.Interface) {
  if (!ROLE_ID.test(roleID)) return
  const files = yield* Effect.promise(() => roleFiles())
  const prefix = `${roleID}/`
  const entries = Object.entries(files).filter(([key]) => key.startsWith(prefix))
  if (entries.length === 0) return

  const root = path.join(Global.Path.home, ".jyycode", "role", roleID)
  if (yield* fs.existsSafe(root)) return

  for (const [key, source] of entries) {
    const target = path.join(root, ...key.slice(prefix.length).split("/"))
    const content = yield* fs.readFile(source).pipe(
      Effect.catch((error) => {
        log.error("failed to read built-in role file", { source, error })
        return Effect.succeed(undefined as Uint8Array | undefined)
      }),
    )
    if (content === undefined) continue
    yield* fs.writeWithDirs(target, content).pipe(
      Effect.catch((error) => {
        log.error("failed to seed built-in role file", { target, error })
        return Effect.void
      }),
    )
  }
  log.info("seeded built-in role", { roleID, files: entries.length })
})

export * as BuiltinRoles from "./builtin-roles"
