// 生成 desktop tokens.css 的颜色块（仅颜色部分；其余 CSS 变量保持手写）
// 运行：bun run --cwd packages/design-tokens generate
// 校验：bun run --cwd packages/design-tokens generate && git diff --exit-code
import { writeFileSync, readFileSync } from "node:fs"
import { resolve } from "node:path"
import { paperLight, cssVars } from "../src/tokens"

const appCss = resolve(import.meta.dir, "../../app/src/styles/tokens.css")
const css = readFileSync(appCss, "utf8")
const lines = css.split("\n")
const start = lines.findIndex((l) => l.includes("/* DESIGN TOKENS: generated by @jyycode-ai/design-tokens"))
const end = start >= 0 ? lines.findIndex((l, i) => i > start && l.trim().startsWith("/* END DESIGN TOKENS")) : -1
const block = [
  "/* DESIGN TOKENS: generated by @jyycode-ai/design-tokens. Do not edit by hand. */",
  ...Object.entries(cssVars(paperLight)).map(([k, v]) => `  ${k}: ${v};`),
  "/* END DESIGN TOKENS */",
].join("\n")

if (start >= 0 && end >= 0) {
  writeFileSync(appCss, [...lines.slice(0, start), block, ...lines.slice(end + 1)].join("\n"))
  console.log("tokens.css color block regenerated")
} else {
  console.error("tokens.css 中未找到 DESIGN TOKENS 标记块；请先在 tokens.css 中插入标记")
  process.exitCode = 1
}
