import crypto from "node:crypto"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { EventV2 } from "../packages/core/src/event"
import "../packages/core/src/catalog"
import "../packages/core/src/session-event"

export type EventCatalogEntry = {
  type: string
  version: number
  aggregate: string
  ignorable: boolean
  schema_hash: string
  projector: string
}

export type EventCatalogOptions = {
  rootDir?: string
  check?: boolean
}

const catalogPath = (rootDir: string) => path.join(rootDir, "docs", "generated", "event-catalog.md")

function canonical(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(canonical)
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, item]) => [key, canonical(item)]),
    )
  if (typeof value === "bigint") return `${value}n`
  return value
}

function schemaHash(definition: EventV2.Definition) {
  const ast = (definition.data as unknown as { ast?: unknown }).ast
  if (!ast) throw new Error(`Event ${definition.type} does not expose a schema AST`)
  return crypto
    .createHash("sha256")
    .update(JSON.stringify(canonical(ast)))
    .digest("hex")
}

/**
 * EventV2's durable session events are statically projected by the kernel's
 * session projector. Unversioned catalog notifications are intentionally not
 * durable facts and are excluded from the catalog.
 */
export async function buildEventCatalog(_rootDir = process.cwd()): Promise<EventCatalogEntry[]> {
  return [...EventV2.registry.values()]
    .filter((definition): definition is EventV2.Definition & { version: number; aggregate: string } => {
      return definition.version !== undefined && definition.aggregate !== undefined
    })
    .map((definition) => ({
      type: definition.type,
      version: definition.version,
      aggregate: definition.aggregate,
      ignorable: definition.ignorable === true,
      schema_hash: schemaHash(definition),
      projector: "packages/jyycode/src/session/projectors-next.ts",
    }))
    .sort((left, right) => left.type.localeCompare(right.type) || left.version - right.version)
}

export function renderEventCatalog(entries: readonly EventCatalogEntry[]) {
  const rows = entries.map(
    (entry) =>
      `| ${entry.type} | ${entry.version} | ${entry.aggregate} | ${entry.ignorable ? "yes" : "no"} | ${entry.schema_hash} | ${entry.projector} |`,
  )
  return [
    "# EventV2 Event Catalog",
    "",
    "This file is generated by `script/verify-event-catalog.ts`; edit the EventV2 definition and projector registry instead.",
    "",
    "A durable event is versioned and has an aggregate. Schema hashes are SHA-256 digests of the canonical Effect Schema AST.",
    "Any type/version deletion or schema hash change must be reviewed with an explicit migration note before updating this file.",
    "",
    "| Type | Version | Aggregate | Ignorable | Schema hash | Projector |",
    "| --- | ---: | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n")
}

export async function verifyEventCatalog(options: EventCatalogOptions = {}) {
  const rootDir = path.resolve(options.rootDir ?? process.cwd())
  const expected = renderEventCatalog(await buildEventCatalog(rootDir))
  const pathname = catalogPath(rootDir)
  if (!options.check) {
    await mkdir(path.dirname(pathname), { recursive: true })
    await writeFile(pathname, expected, "utf8")
    return { ok: true as const, path: pathname, changed: true as const }
  }
  let actual: string
  try {
    actual = await readFile(pathname, "utf8")
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT")
      return { ok: false as const, path: pathname, message: "generated event catalog is missing" }
    throw error
  }
  if (actual !== expected)
    return {
      ok: false as const,
      path: pathname,
      message: "event catalog is stale; review schema/type changes and add an explicit migration note",
    }
  return { ok: true as const, path: pathname, changed: false as const }
}

if (import.meta.main) {
  const result = await verifyEventCatalog({ check: process.argv.includes("--check") })
  if (!result.ok) {
    console.error(result.message)
    process.exitCode = 1
  } else {
    console.log(`${result.changed ? "Generated" : "Verified"} event catalog: ${result.path}`)
  }
}
